apiVersion: medialive.aws.upbound.io/v1beta2
kind: Input
metadata:
  annotations:
    meta.upbound.io/example-id: medialive/v1beta2/input
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    inputSecurityGroupsRefs:
    - name: example
    name: example-input
    region: us-west-1
    type: UDP_PUSH

---

apiVersion: medialive.aws.upbound.io/v1beta1
kind: InputSecurityGroup
metadata:
  annotations:
    meta.upbound.io/example-id: medialive/v1beta2/input
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    region: us-west-1
    whitelistRules:
    - cidr: 10.0.0.8/32
