apiVersion: iam.aws.upbound.io/v1beta1
kind: User
metadata:
  annotations:
    meta.upbound.io/example-id: iam/v1beta1/user
  labels:
    testing.upbound.io/example-name: lb
  name: lb
spec:
  forProvider:
    path: /system/

---

apiVersion: iam.aws.upbound.io/v1beta1
kind: AccessKey
metadata:
  annotations:
    meta.upbound.io/example-id: iam/v1beta1/user
  labels:
    testing.upbound.io/example-name: lb
  name: lb
spec:
  forProvider:
    userSelector:
      matchLabels:
        testing.upbound.io/example-name: lb
